# 第二章

# 2.1认识Numpy数组

In [1]:
import numpy as np #导入Numpy工具包

In [2]:
data=np.arange(12).reshape(3,4) #创建一个3行4列的数组

In [3]:
data #输出

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [4]:
type(data) #查看数组的类型

numpy.ndarray

In [5]:
data.ndim #获取了数组的维度个数，返回为2，表示二维数组

2

In [6]:
data.shape #获取数组的维度，返回（3，4），表示数组3行4列

(3, 4)

In [7]:
data.size #获取数组中元素的总个数，返回结果为12，表示数组中一共有12个元素

12

In [8]:
data.dtype #获取了元素的具体类型，返回为dtype('int32'),表示元素数组为int32

dtype('int32')

# 2.2 创建Numpy数组

# 创建ndarray对象，可以使用array（）还可以通过zeros（），ones（），empty（），arange（）

In [9]:
import numpy as np

In [10]:
data1=np.array([1,2,3]) #创建一个一维数组 

In [11]:
data1

array([1, 2, 3])

In [12]:
data2=np.array([[1,2,3],[4,5,6]]) #创建一个二维数组
data2

array([[1, 2, 3],
       [4, 5, 6]])

In [13]:
np.zeros((3,4)) #通过zeros()函数创建元素都是0的数组

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [14]:
np.ones((3,4)) #通过ones()函数创建元素都是1的数组

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [15]:
np.empty((5,2)) #通过empty（）函数创建一个数组，但只分配了内存空间，填充的元素是随机的

array([[1.40173880e-311, 2.32210854e-322],
       [0.00000000e+000, 0.00000000e+000],
       [2.22522868e-306, 1.16095484e-028],
       [6.97283618e+228, 2.09603058e-110],
       [2.91237123e+257, 4.71294503e+257]])

In [16]:
np.arange(1,20,5) #创建一个等差数组，类似于range（），只不过arange（）函数返回的结果是数组，而不是列表

array([ 1,  6, 11, 16])

In [17]:
np.array([1,2,3,4],float) #在创ndarray对象时，可以显式声明数组元素的类型。

array([1., 2., 3., 4.])

In [20]:
np.ones((2,3),dtype='float64')

array([[1., 1., 1.],
       [1., 1., 1.]])

# 2.3  ndarray对象的数据类型

# 2.3.1  查看数据类型

In [21]:
data_one=np.array([[1,2,3],[4,5,6]]) #使用dtype属性查看data_one对象的数据类型
data_one.dtype.name

'int32'

# 2.3.2  转换数据类型

In [22]:
data=np.array([[1,2,3],[4,5,6]])
data.dtype

dtype('int32')

In [23]:
float_data=data.astype(np.float64) #数据类型转换为float64, 整型转换为浮点型。
float_data.dtype

dtype('float64')

In [24]:
float_data=np.array([1.2,2.3,3.5])
float_data

array([1.2, 2.3, 3.5])

In [25]:
int_data=float_data.astype(np.int64) #数据类型转换为int64,若希望将数据的类型由浮点型转换为整型，则需要将小数点后面的部分截掉。
int_data

array([1, 2, 3], dtype=int64)

In [26]:
#如果数组中的元素是字符串类型的，且字符串中的每个字符都是数字，则也可以使用astype（）方法将字符串转换为数值类型。
str_data=np.array(['1','2','3'])
int_data=str_data.astype(np.int64)
int_data

array([1, 2, 3], dtype=int64)

# 2.4   数组运算

# 2.4.1  矢量化运算

In [27]:
import numpy as np
data1=np.array([[1,2,3],[4,5,6]])
data2=np.array([[1,2,3],[4,5,6]])
data1+data2  #数组相加，相同位置进行加减乘除

array([[ 2,  4,  6],
       [ 8, 10, 12]])

In [28]:
data1*data2 #数组相乘

array([[ 1,  4,  9],
       [16, 25, 36]])

In [29]:
data1-data2  #数组相减

array([[0, 0, 0],
       [0, 0, 0]])

In [30]:
data1/data2  #数组相除

array([[1., 1., 1.],
       [1., 1., 1.]])

# 2.4.2  数组广播

In [31]:
#数组在进行矢量化运算时，要求数组的形状是相等的。当形状不相等的数组执行算数运算的时候，就会出现广播机制，
#该机制会对数组进行扩展，使数组的shape属性值一样，这样就可以进行矢量化运算了。
import numpy as np
arr1=np.array([[0],[1],[2],[3]])
arr1.shape

(4, 1)

In [32]:
arr2=np.array([1,2,3])
arr2.shape

(3,)

In [33]:
arr1+arr2 #arr1的shape使（4，1），arr2的shape是（3，）这两个数组要是进行相加，广播机制会对数组arr1和arr2都进行拓展，
          #使数组都变成（4，3）。


array([[1, 2, 3],
       [2, 3, 4],
       [3, 4, 5],
       [4, 5, 6]])

# 2.4.3 数组与标量之间的运算

In [34]:
import numpy as np
data1=np.array([[1,2,3],[4,5,6]])
data2=10
data1+data2  #数组相加

array([[11, 12, 13],
       [14, 15, 16]])

In [35]:
data1*data2 #数组相乘

array([[10, 20, 30],
       [40, 50, 60]])

In [36]:
data1-data2  #数组相减

array([[-9, -8, -7],
       [-6, -5, -4]])

In [37]:
data1/data2  #数组相除

array([[0.1, 0.2, 0.3],
       [0.4, 0.5, 0.6]])

# 2.5  ndarray的索引和切片

# 2.5.1  整数索引和切片的基本使用

In [38]:
import numpy as np
arr=np.arange(8)  #创建一个一维数组
arr

array([0, 1, 2, 3, 4, 5, 6, 7])

In [39]:
arr[5] #获取索引为5的元素

5

In [40]:
arr[3:5] #获取索引为3-5的元素，但不包括5

array([3, 4])

In [41]:
arr[1:6:2] #获取索引为1-6的元素，步长为2

array([1, 3, 5])

In [42]:
arr2d=np.array([[1,2,3],[4,5,6],[7,8,9]]) #创建一个二维数组
arr2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [43]:
arr2d[1]  #获取索引为1的元素，此获取的元素就是一个一维数组。

array([4, 5, 6])

In [44]:
arr2d[0,1] #获取位于第0行第一列的元素，此获取为单个元素  行属与列数都是从0开始。

2

In [45]:
arr2d[:2]  #传入一个切片的示例代码

array([[1, 2, 3],
       [4, 5, 6]])

In [46]:
arr2d[0:2,0:2] #传入两个切皮

array([[1, 2],
       [4, 5]])

In [47]:
arr2d[1,:2] #切片与整数索引混合使用

array([4, 5])

# 2.5.2  花式（数组）  索引的基本使用

In [49]:
#创建一个4行4列的二维数组
demo_arr=np.empty((4,4)) #创建一个空数组
for i in range(4):
    demo_arr[i]=np.arange(i,i+4) #动态地为数组添加元素

In [50]:
demo_arr

array([[0., 1., 2., 3.],
       [1., 2., 3., 4.],
       [2., 3., 4., 5.],
       [3., 4., 5., 6.]])

In [51]:
demo_arr[[0,2]]  #获取索引为【0，2】的元素，将[0，2]作为索引，分别获取demo_arr中素银0对应的那一行数据以及索引2对应的一行数据。

array([[0., 1., 2., 3.],
       [2., 3., 4., 5.]])

In [52]:
demo_arr[[1,3],[1,2]] #获取索引为（1，1）和（3，2）的元素

array([2., 5.])

# 2.5.2  布尔型索引的基本使用

In [61]:
#存储学生姓名的数组
student_name=np.array(['tom','Lily','Jack','Rose'])
student_name

array(['tom', 'Lily', 'Jack', 'Rose'], dtype='<U4')

In [62]:
#存储学生成绩的数组
student_score=np.array([[79,88,80],[89,90,92],[83,78,85],[78,76,80]])
student_score

array([[79, 88, 80],
       [89, 90, 92],
       [83, 78, 85],
       [78, 76, 80]])

In [63]:
#对student_name和字符串“Jake”通过预算符产生一个布尔型数组
student_name=='Jack'

array([False, False,  True, False])

In [64]:
#将返回的布尔型数组作为索引应用于存储成绩的数组student_score,
#返回的数据是True所对应的行
student_score[student_name=='Jack']

array([[83, 78, 85]])

In [65]:
student_score[student_name=='Jack',:1] #布尔型数组与切片的混合使用

array([[83]])

# 2.6  数组的转置和轴的对称

In [69]:
arr=np.arange(12).reshape(3,4)
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [70]:
arr.T  #使用T属性进行转置

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

In [71]:
#对于高维度的数组而言，transpose（）方法需要得到一个由轴编号组成的元组，才能对这些轴进行转置。
arr=np.arange(16).reshape((2,2,4))
arr

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]]])

In [72]:
arr.shape #arr的shape是（2，2，4），表示是一个三维数组，也就是说有三个轴，每个轴都对应着一个编号，分别是0、1、2.

(2, 2, 4)

In [73]:
arr.transpose(1,2,0)  #使用transpose（）方法对数组进行转置；当使用transpose（）方法对数组的shape进行变幻时，
                      #需要以元组的形式传入shape的编号，比如（1，2，0）

array([[[ 0,  8],
        [ 1,  9],
        [ 2, 10],
        [ 3, 11]],

       [[ 4, 12],
        [ 5, 13],
        [ 6, 14],
        [ 7, 15]]])

In [74]:
arr #有时我们可能只需要两个轴，这时我们可以使用ndarray提供的swapaxes（）实现，该方法需要接受一对轴编号，

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]]])

In [75]:
arr.swapaxes(1,0)  #使用swapaxes方法插入一对小括号对数组进行转置

array([[[ 0,  1,  2,  3],
        [ 8,  9, 10, 11]],

       [[ 4,  5,  6,  7],
        [12, 13, 14, 15]]])

# 2.7  Numpy通用函数

# 一元通用函数

In [76]:
arr=np.array([4,9,16])  #计算数组的平方跟
np.sqrt(arr)

array([2., 3., 4.])

In [77]:
np.abs(arr) #计算数组的绝对值

array([ 4,  9, 16])

In [78]:
np.square(arr) #计算数组的平方

array([ 16,  81, 256], dtype=int32)

# 二元通用函数

In [79]:
x=np.array([12,9,13,15])
y=np.array([11,10,4,8])
np.add(x,y)  #计算两个数组的和

array([23, 19, 17, 23])

In [81]:
np.maximum(x,y) #两个数组元素级最大值的比较

array([12, 10, 13, 15])

In [82]:
np.multiply(x,y)#计算两个数组的乘积

array([132,  90,  52, 120])

In [83]:
np.greater(x,y) #执行元素级的比较操作

array([ True, False,  True,  True])

# 2.8  利用Numpy数组进行数据处理

# 2.8.1  讲条件逻辑转换为数组运算

In [84]:
#假设有两个数值型数组和一个布尔型数组，是true的从arr_x中出来一个值，是false是从arr_y中出来一个值，而arr_con是一个判断条件
arr_x=np.array([1,5,7])
arr_y=np.array([2,6,8])
arr_con=np.array([True,False,True])
result=np.where(arr_con,arr_x,arr_y)
result

array([1, 6, 7])

# 2.8.2  数组统计运算

In [85]:
arr=np.arange(10)
arr.sum()  #求和  ,不包含十

45

In [86]:
arr.mean() #求平均值

4.5

In [87]:
arr.min()  #求最小值

0

In [89]:
arr.max()  #求最大值

9

In [90]:
arr.argmin() #求最小的索引

0

In [91]:
arr.argmax()  #求最大的索引

9

In [93]:
arr.cumsum()   #计算元素的累计和

array([ 0,  1,  3,  6, 10, 15, 21, 28, 36, 45], dtype=int32)

In [94]:
arr.cumprod()  #计算元素的累计积

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=int32)

# 2.8.3  数组排序

In [96]:
arr=np.array([[6,2,7],[3,6,2],[4,3,2]])
arr

array([[6, 2, 7],
       [3, 6, 2],
       [4, 3, 2]])

In [99]:
arr.sort()
arr   #对数组中的元素进行排序  通过sort（）方法实现，有小到大

array([[2, 6, 7],
       [2, 3, 6],
       [2, 3, 4]])

In [100]:
arr=np.array([[6,2,7],[3,6,2],[4,3,2]])
arr

array([[6, 2, 7],
       [3, 6, 2],
       [4, 3, 2]])

In [101]:
arr.sort(0)   #沿着编号为0的轴对元素排序
arr

array([[3, 2, 2],
       [4, 3, 2],
       [6, 6, 7]])

# 2.8.4  检索数组元素

In [102]:
arr=np.array([[1,-2,-7],[-3,6,2],[-4,3,2]])
arr

array([[ 1, -2, -7],
       [-3,  6,  2],
       [-4,  3,  2]])

In [103]:
np.any(arr>0)  #arr的所有元素是否有一个大于0

True

In [104]:
np.all(arr>0)   #arr的所有元素是否都大于0

False

# 2.8.5  唯一化及其他集合逻辑

In [105]:
arr=np.array([12,11,34,23,12,8,11])  #用unique（）方法找出唯一值，并排序
np.unique(arr)

array([ 8, 11, 12, 23, 34])

In [107]:
np.in1d(arr,[11,12])  #in1d()函数用于判断数组中元素是否在另一个数组中存在，该函数返回的是一个布尔型数组。

array([ True,  True, False, False,  True, False,  True])

# 2.9线性代数模块

In [108]:
arr_x=np.array([[1,2,3],[4,5,6]])
arr_y=np.array([[1,2],[3,4],[5,6]])
arr_x.dot(arr_y)    #等价于np.dot(arr_x,arr_y)

array([[22, 28],
       [49, 64]])

# 2.10   随机数模块

In [109]:
import numpy as np
np.random.rand(3,3)  #随机生成一个二维数组

array([[0.69288765, 0.86531753, 0.25883397],
       [0.17876897, 0.72271756, 0.31263224],
       [0.42152448, 0.65259249, 0.29938282]])

In [110]:
np.random.rand(2,3,3)  #随机生成一个三维数组

array([[[0.1066597 , 0.07222326, 0.40381626],
        [0.31291472, 0.36061902, 0.26916716],
        [0.06143624, 0.71781003, 0.69151021]],

       [[0.8154467 , 0.34945785, 0.03620165],
        [0.07165757, 0.93985493, 0.66736349],
        [0.1249093 , 0.76460988, 0.15418136]]])

In [111]:
#使用seed（）函数代码
np.random.seed(0) #生成随机数的种子
np.random.rand(5) #随机生成包含5个元素的浮点数组

array([0.5488135 , 0.71518937, 0.60276338, 0.54488318, 0.4236548 ])

In [112]:
np.random.seed(0)
np.random.rand(5)

array([0.5488135 , 0.71518937, 0.60276338, 0.54488318, 0.4236548 ])

In [113]:
np.random.seed()
np.random.rand(5)

array([0.15412649, 0.97907899, 0.36420409, 0.08847944, 0.16286934])